tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/homebrew-services"

brew "git"
brew "curl"
brew "lv"
brew "imagemagick"
brew "rbenv"
brew "ruby-build"
brew "postgresql@15"
brew "fish"
brew "nodenv"
brew "node-build"
brew "openjdk@11"

cask_args appdir: "/Applications"
cask "iterm2"
cask "visual-studio-code"
cask "google-chrome"
cask "slack"
cask "docker"

vscode "vscodevim.vim"
vscode "scalameta.metals"
vscode "rust-lang.rust-analyzer"
